name: Spring Boot CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Look for gradlew
      run: find / -type f -name "gradlew"

    - name: Grant permission for gradlew
      run: chmod +x remora/gradlew

    - name: Clean build
      run: ./remora/gradlew clean build

    - name: Build with Gradle
      run: ./remora/gradlew build -x test

    - name: Test with Gradle
      run: ./remora/gradlew test

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }}
      with:
        files: build/test-results/**/*.xml